### ISSUE TITLE
after few minutes I am getting this

### ISSUE THREAD

**Issue by roozbehid-ic** [jsargiot/visual-coverage#16] opened 2017-03-24 22:28 UTC
After few minutes running on the results of a project compiled in C#,C++ with Vsiaul Studio 2015 I am getting this :

Unhandled Exception: System.Xml.XmlException: '<', hexadecimal value 0x3C, is an
 invalid attribute character. Line 1798, position 35.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char qu
oteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XPath.XPathDocument.LoadFromReader(XmlReader reader, XmlSpace s
pace)
   at System.Xml.XPath.XPathDocument..ctor(XmlReader reader, XmlSpace space)
   at System.Xml.Xsl.Runtime.XmlQueryContext.ConstructDocument(Object dataSource
, String uriRelative, Uri uriResolved)
   at System.Xml.Xsl.Runtime.XmlQueryContext..ctor(XmlQueryRuntime runtime, Obje
ct defaultDataSource, XmlResolver dataSources, XsltArgumentList argList, Whitesp
aceRuleLookup wsRules)
   at System.Xml.Xsl.Runtime.XmlQueryRuntime..ctor(XmlQueryStaticData data, Obje
ct defaultDataSource, XmlResolver dataSources, XsltArgumentList argList, XmlSequ
enceWriter seqWrt)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver da
taSources, XsltArgumentList argumentList, XmlSequenceWriter results)
   at System.Xml.Xsl.XmlILCommand.Execute(Object defaultDocument, XmlResolver da
taSources, XsltArgumentList argumentList, XmlWriter writer)
   at System.Xml.Xsl.XslCompiledTransform.Transform(XmlReader input, XmlWriter r
esults)
   at VisualCoverage.Core.HtmlReport.Execute(ProjectElement project)
   at VisualCoverage.Console.CmdDriver.Main(String[] args)

**Comment by jsargiot** [comment] 2017-03-25 20:11
Closing as it's a duplicate of #14

**Closed by jsargiot** 2017-03-25 20:11 UTC
